"""Add event summaries table

Revision ID: d9089e623c5c
Revises: 5129f15bfe3e
Create Date: 2025-11-04 11:47:01.384377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9089e623c5c'
down_revision: Union[str, Sequence[str], None] = '5129f15bfe3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_summaries_event_id'), 'event_summaries', ['event_id'], unique=True)
    op.create_index(op.f('ix_event_summaries_id'), 'event_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_summaries_id'), table_name='event_summaries')
    op.drop_index(op.f('ix_event_summaries_event_id'), table_name='event_summaries')
    op.drop_table('event_summaries')
    # ### end Alembic commands ###
